# Generated by Django 6.0.3 on 2026-04-04 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_poll_alter_user_display_name_polldateoption_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PollDateOption',
            new_name='PollDate',
        ),
    ]
