# Generated by Django 6.0.3 on 2026-04-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(default='Tyler', max_length=120),
            preserve_default=False,
        ),
    ]
